export const projects = [
  {
    id: 1,
    name: 'Dflix filmes',
    image: '/img/projects/dflix.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'React JS',
    url: 'https://dflix-project.netlify.app/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 2,
    name: 'Studio Club',
    image: '/img/projects/studioClub.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'Laravel PHP',
    url: 'https://studioclub.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 3,
    name: 'Clinica Natalli Landi',
    image: '/img/projects/clinicaNatalliLandi.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'Laravel PHP',
    url: 'https://clinicanatallilandi.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 4,
    name: 'Casa Sharani',
    image: '/img/projects/casaSharani.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'Laravel PHP',
    url: 'https://casasharani.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 5,
    name: 'Dra. Andreá Hokama',
    image: '/img/projects/andreaHokama.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'Laravel PHP',
    url: 'https://andreahokamaodontologia.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 6,
    name: 'Zeidan Consultoria e Seguros',
    image: '/img/projects/zeidanConsultoria.webp',
    text: 'Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar Lorem ipsum dolar',
    language: 'PHP | Javascript',
    url: 'https://zeidanconsultoriaeseguros.com.br/',
    url_github: 'https://www.google.com.br',
  },
]