export const projects = [
  {
    id: 1,
    name: 'Dflix filmes',
    image: '/img/projects/dflix.webp',
    text: 'Desenvolvi uma biblioteca de filmes em React JS que realiza consultas dinâmicas à API do IMDb para buscar informações sobre os filmes.',
    language: 'React JS',
    url: 'https://dflix-project.netlify.app/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 2,
    name: 'Studio Club',
    image: '/img/projects/studioClub.webp',
    text: 'Aqui está o website institucional que desenvolvi para a Engenho de Imagens, utilizando as linguagens de programação Laravel e Javascript para garantir sua robustez.',
    language: 'Laravel PHP',
    url: 'https://studioclub.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 3,
    name: 'Clinica Natalli Landi',
    image: '/img/projects/clinicaNatalliLandi.webp',
    text: 'Apresento o website institucional desenvolvido para a Engenho de Imagens, destacando sua robustez alcançada por meio das linguagens de programação Laravel e Javascript.',
    language: 'Laravel PHP',
    url: 'https://clinicanatallilandi.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 4,
    name: 'Casa Sharani',
    image: '/img/projects/casaSharani.webp',
    text: 'Apresento o website institucional desenvolvido para a Engenho de Imagens, destacando sua robustez alcançada por meio das linguagens de programação Laravel e Javascript.',
    language: 'Laravel PHP',
    url: 'https://casasharani.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 5,
    name: 'Dra. Andreá Hokama',
    image: '/img/projects/andreaHokama.webp',
    text: 'Apresento o website institucional desenvolvido para a Engenho de Imagens, destacando sua robustez alcançada por meio das linguagens de programação Laravel e Javascript.',
    language: 'Laravel PHP',
    url: 'https://andreahokamaodontologia.com.br/',
    url_github: 'https://www.google.com.br',
  },
  {
    id: 6,
    name: 'Zeidan Consultoria',
    image: '/img/projects/zeidanConsultoria.webp',
    text: 'Apresento a landing page desenvolvida para a Engenho de Imagens, alcançada por meio das linguagens de programação PHP e Javascript.',
    language: 'PHP | Javascript',
    url: 'https://zeidanconsultoriaeseguros.com.br/',
    url_github: 'https://www.google.com.br',
  },
]